export const RESTART_REGISTER_RESPONSE = "RESTART_REGISTER_RESPONSE";

export const REGISTER_LOADING = "REGISTER_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_ERROR = "REGISTER_ERROR";

export const REGISTER_CODE_ERROR = "REGISTER_ERROR";

export const RESTART_LOGIN_RESPONSE = "RESTART_LOGIN_RESPONSE";

export const LOGIN_LOADING = "LOGIN_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGIN_CODE_ERROR = "LOGIN_ERROR";
